claims:
  #identifier of the server or system
  iss: "Task Manager App"
  #date/time when token was issued (default now)
  iat:
  #expiration time, at which the token is no longer valid (based on ttl)
  exp:
  #time after what token will be valid
  nbf:
  #Audience (user email)
  aud:
  #subject
  sub:
#secret key
secret: "SomeSecretKey"
#minites - duration on which token will be valid
ttl: 60
#minutes - duration on which refresh token will be valid
refresh_ttl: 20160
