sender:
  name: "Some Sender"
  email: "sender@mail.com"
connection:
  host: smtp.mailtrap.io
  port: 465
  username: 7becbf096c9b34
  password: deb0640e7fac43
  # plain, login, cram_md5
  auth: plain
  tls: true