version: '2'

services:
  # TODO: username password seeds broadcast args
  cassandra:
    image: cassandra:3.11.1
    ports:
      - ${CASSANDRA_SYNC_PORT}:7000
      - ${CASSANDRA_SSL_SYNC_PORT}:7001
      - ${CASSANDRA_JMX_MONITORING_PORT}:7199
      - ${CASSANDRA_THRIFT_CLIENT_PORT}:9160
      - ${CASSANDRA_CLIENT_PORT}:9042
    volumes:
      - cassandra-storage:/var/lib/cassandra

  react:
    image: node:latest
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
    command: bash -c "npm install && npm install -g webpack && npm start"

  zoo:
    image: zookeeper:3.4.9
    hostname: zoo
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo:2888:3888

  kafka:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # name:partitions:replicas
      KAFKA_CREATE_TOPICS: "test-topic-1:1:1"
    depends_on:
      - zoo

volumes:
  cassandra-storage:

