export const HANDLE_DRAWER_TOGGLE = 'HANDLE_DRAWER_TOGGLE'
export const HANDLE_PAGE_TITLE_CHANGE = 'HANDLE_PAGE_TITLE_CHANGE'
export const HANDLE_ERROR_MESSAGE = 'HANDLE_ERROR_MESSAGE'
export const HANDLE_NOTIFICATION_MESSAGE = 'HANDLE_NOTIFICATION_MESSAGE'