export const HANDLE_NAME_UPDATE_ISSUE_INPUT = 'HANDLE_GOAL_UPDATE_ISSUE_INPUT'
export const HANDLE_DESC_UPDATE_ISSUE_INPUT = 'HANDLE_DESC_UPDATE_ISSUE_INPUT'
export const HANDLE_STATUS_UPDATE_ISSUE_INPUT = 'HANDLE_STATUS_UPDATE_ISSUE_INPUT'
export const HANDLE_ESTIMATE_UPDATE_ISSUE_INPUT = 'HANDLE_ESTIMATE_UPDATE_ISSUE_INPUT'
export const HANDLE_ISSUES_LOADED = 'HANDLE_ISSUES_LOADED'
export const HANDLE_CURRENT_ISSUE = 'HANDLE_CURRENT_ISSUE'
export const SET_ISSUES_HIERARCHY = "SET_ISSUES_HIERARCHY"
