export const HANDLE_PROJECTS_LOADED = 'HANDLE_PROJECTS_LOADED'
export const HANDLE_PROJECT_SELECTED = 'HANDLE_PROJECT_SELECTED'
export const HANDLE_PROJECT_USERS = 'HANDLE_PROJECT_USERS'
export const HANDLE_USERS_LIST = 'HANDLE_USERS_LIST'
